name: Build OpenWrt
on: 
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  #REPO_URL: https://github.com/openwrt/openwrt
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: false
  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    
#    - name: Checkout
 #     uses: actions/checkout@main
 
    - name: config test
      run: |
        cat >  .config << EOF
        CONFIG_TARGET_ramips=y
        ONFIG_TARGET_ramips_mt7621=y
        CONFIG_TARGET_ramips_mt7621_DEVICE_hiwifi_hc5962=y
        EOF
        ls -al && cat .config
 

    
    - name: Installation depends
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
        sudo timedatectl set-timezone "$TZ"
    
    - name: test
      run: |
        sudo whoami && id && pwd && ls -al
        
    - name : clone & feeds install
      run: |
        git clone https://github.com/coolsnowwolf/lede openwrt
        df -T
        #git clone https://github.com/openwrt/openwrt
        cd openwrt
        cat feeds.conf.default
        echo 'src-git small8 https://github.com/kenzok8/small-package' >>feeds.conf.default
        cat feeds.conf.default
        ./scripts/feeds clean
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
    - name: test
      run:
        sudo whoami && id && pwd && ls -al
 
    - name: config
      run: |
        cd openwrt
        sed -i 's/192.168.1.1/192.168.9.199/g' package/base-files/files/bin/config_generate
        cat > .config << EOF
        CONFIG_TARGET_ramips=y
        CONFIG_TARGET_ramips_mt7621=y
        CONFIG_TARGET_ramips_mt7621_DEVICE_hiwifi_hc5962=y                 
        EOF
        ls -al && cat .config | grep -Ev '^$|#'
        
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}  
        
 #   - name: Load custom feeds
 #     run: |
#        [ -e $FEEDS_CONF ] && cp $FEEDS_CONF openwrt/feeds.conf.default
#        chmod +x $DIY_P1_SH
#        cd openwrt
#        $GITHUB_WORKSPACE/$DIY_P1_SH
        
#    - name: Load custom configuration
#      run: |
#        [ -e files ] && mv files openwrt/files
#        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
#        chmod +x $DIY_P2_SH
 #       cd openwrt
#        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: test
      run: |
        cd openwrt
        sudo whoami && id && pwd && ls -al   
        
    - name: Generate config file
      run: |
        cd openwrt
        cat .config | grep -Ev '^$|#'
        make defconfig
        ./scripts/diffconfig.sh > seed.config
        
    - name: Download package
      run: |
        cd openwrt && make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    - name: Build
      run: |
        cd openwrt
        make -j$(nproc)
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt
        path: openwrt/bin
